CREATE TABLE b_kit_filter_prop_settings (
	ID int(18) NOT NULL AUTO_INCREMENT,
	PROPERTY_ID int(11) NOT NULL,
	HINT_TYPE varchar(255) NOT NULL DEFAULT 'html',
	HINT longtext,
	VIEW varchar(255) NOT NULL,
	SLIDER_STEP double(18,8) unsigned NOT NULL DEFAULT '0.0',
	SLIDER_UNITS varchar(255) NOT NULL DEFAULT '',
	LIST_SIZE int(8) unsigned NOT NULL DEFAULT '0',
	LIST_MULTI char(1) NOT NULL DEFAULT 'N',
	VALUES_CNT int(8) NOT NULL DEFAULT '0',
	SORT varchar(255) NOT NULL DEFAULT 'NAME',
	SORT_ORDER varchar(255) NOT NULL DEFAULT 'ASC',
	PRIMARY KEY (ID)
);